# Solving a System of Linear Equations by Matrix Inversion

This notebook demonstrates how to solve a system of two linear equations using matrix inversion with NumPy. Each step is explained and shown in code and output.

**Learning Objectives:**
- Understand the matrix inversion method for solving systems of equations
- Use NumPy to perform matrix operations in Python
- Interpret step-by-step solutions

**Prerequisites:**
- Basic Python
- Familiarity with matrices and linear algebra

In [1]:
# Import the required libraries
import numpy as np

## Step 1: Define the Coefficient and Constant Matrices
We define the coefficient matrix A and the constant matrix b.

In [2]:
# Define the coefficient matrix A and the constant matrix b
A = np.array([[2, 3], [4, 1]])
b = np.array([6, 5])
A, b

(array([[2, 3],
        [4, 1]]),
 array([6, 5]))

## Step 2: Calculate the Inverse of Matrix A
We calculate the inverse of the coefficient matrix.

In [3]:
# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)
A_inv

array([[-0.1,  0.3],
       [ 0.4, -0.2]])

## Step 3: Solve for X Using Matrix Multiplication
We solve for the solution vector X using matrix multiplication.

In [4]:
# Solve for X using matrix multiplication
X = np.dot(A_inv, b)
X

array([0.9, 1.4])

## Step 4: Display the Solution for x and y
We extract and display the values of x and y from the solution vector.

In [5]:
# Display the solution for x and y
x, y = X
print(f"Solution: x = {x}, y = {y}.")

Solution: x = 0.8999999999999999, y = 1.4000000000000004.


## Summary
- We solved a system of linear equations using matrix inversion.
- Each step was performed using NumPy matrix operations.
- The solution is displayed for x and y.
- This method is efficient for small systems and for teaching matrix algebra techniques.