# Solving a System of Linear Equations by Gaussian Elimination

This notebook demonstrates how to solve a system of two linear equations using Gaussian elimination with NumPy. Each step is explained and shown in code and output.

**Learning Objectives:**
- Understand the Gaussian elimination method for solving systems of equations
- Use NumPy to perform matrix operations in Python
- Interpret step-by-step solutions

**Prerequisites:**
- Basic Python
- Familiarity with matrices and linear algebra

In [1]:
# Import the required libraries
import numpy as np

## Step 1: Define the Augmented Matrix
We define the augmented matrix [A|b] for the system.

In [2]:
# Define the augmented matrix [A|b]
augmented_matrix = np.array([[2, 3, 5],
                             [4, -1, 6]], dtype=float)
augmented_matrix

array([[ 2.,  3.,  5.],
       [ 4., -1.,  6.]])

## Step 2: Forward Elimination Process
We perform forward elimination to transform the matrix into upper triangular form.

In [3]:
# Forward elimination process
rows, cols = augmented_matrix.shape
for i in range(rows):
    # Normalize the current row by dividing by the diagonal element
    augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i][i]
    # Eliminate the current variable from the subsequent rows
    for j in range(i + 1, rows):
        augmented_matrix[j] = augmented_matrix[j] - augmented_matrix[j][i] * augmented_matrix[i]
augmented_matrix

array([[ 1.        ,  1.5       ,  2.5       ],
       [-0.        ,  1.        ,  0.57142857]])

## Step 3: Back Substitution Process
We perform back substitution to solve for the variables.

In [4]:
# Back substitution process
solutions = np.zeros(rows)
for i in range(rows - 1, -1, -1):
    solutions[i] = augmented_matrix[i][-1] - np.sum(augmented_matrix[i][i+1:-1] * solutions[i+1:])
solutions

array([1.64285714, 0.57142857])

## Step 4: Display the Solution for x and y
We extract and display the values of x and y from the solution vector.

In [5]:
# Display the solution for x and y
for index, value in zip(['x', 'y'], solutions):
    print(f'{index} = {value:.2f}')

x = 1.64
y = 0.57


## Summary
- We solved a system of linear equations using Gaussian elimination.
- Each step was performed using NumPy matrix operations.
- The solution is displayed for x and y.
- This method is efficient for small systems and for teaching matrix algebra techniques.