# Calculating the Rank of a Matrix

This notebook demonstrates how to calculate the rank of a matrix using NumPy.

**Learning Objectives:**
- Understand the concept of matrix rank
- Use NumPy to compute matrix rank in Python
- Interpret the result in the context of linear algebra

**Prerequisites:**
- Basic Python
- Familiarity with matrices and linear algebra

In [1]:
# Import the required libraries
import numpy as np

## Step 1: Define the Matrix
We define the matrix A.

In [2]:
# Define the matrix A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Step 2: Calculate the Rank
We use NumPy to calculate the rank of matrix A.

In [3]:
# Calculate the rank of matrix A
rank_A = np.linalg.matrix_rank(A)
rank_A

2

## Step 3: Display the Matrix and Its Rank
We display the matrix and its rank.

In [4]:
# Display the matrix and its rank
print("Matrix A:")
print(A)
print(f"\nRank of Matrix A: {rank_A}.")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of Matrix A: 2.


## Summary
- We calculated the rank of a matrix using NumPy.
- The rank indicates the number of linearly independent rows or columns.
- This concept is fundamental in linear algebra and has applications in solving systems of equations.