# Calculating the Eigenvalues of a Matrix

This notebook demonstrates how to calculate the eigenvalues of a matrix using NumPy.

**Learning Objectives:**
- Understand the concept of eigenvalues
- Use NumPy to compute eigenvalues in Python
- Interpret the result in the context of linear algebra

**Prerequisites:**
- Basic Python
- Familiarity with matrices and linear algebra

In [1]:
# Import the required libraries
import numpy as np

## Step 1: Define the Matrix
We define the square matrix A.

In [2]:
# Define a square matrix A
A = np.array([
    [4, 2],
    [1, 3]
])
A

array([[4, 2],
       [1, 3]])

## Step 2: Calculate the Eigenvalues
We use NumPy to calculate the eigenvalues of matrix A.

In [3]:
# Calculate the eigenvalues of matrix A
eigenvalues = np.linalg.eigvals(A)
eigenvalues

array([5., 2.])

## Step 3: Display the Matrix and Its Eigenvalues
We display the matrix and its eigenvalues.

In [4]:
# Display the matrix and its eigenvalues
print("Matrix A:")
print(A)
print("\nEigenvalues of Matrix A:")
print(eigenvalues)

Matrix A:
[[4 2]
 [1 3]]

Eigenvalues of Matrix A:
[5. 2.]


## Summary
- We calculated the eigenvalues of a matrix using NumPy.
- Eigenvalues are important in linear algebra for understanding matrix properties.
- This concept is fundamental in many applications, including systems of equations and transformations.