# Calculating the Eigenvectors of a Matrix

This notebook demonstrates how to calculate the eigenvectors (and eigenvalues) of a matrix using NumPy.

**Learning Objectives:**
- Understand the concept of eigenvectors and eigenvalues
- Use NumPy to compute eigenvectors and eigenvalues in Python
- Interpret the result in the context of linear algebra

**Prerequisites:**
- Basic Python
- Familiarity with matrices and linear algebra

In [1]:
# Import the required libraries
import numpy as np

## Step 1: Define the Matrix
We define the square matrix A.

In [2]:
# Define a square matrix A
A = np.array([
    [4, 2],
    [1, 3]
])
A

array([[4, 2],
       [1, 3]])

## Step 2: Calculate the Eigenvalues and Eigenvectors
We use NumPy to calculate the eigenvalues and eigenvectors of matrix A.

In [3]:
# Calculate the eigenvalues and eigenvectors of matrix A
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues, eigenvectors

(array([5., 2.]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

## Step 3: Display the Matrix, Its Eigenvalues, and Eigenvectors
We display the matrix, its eigenvalues, and eigenvectors.

In [4]:
# Display the matrix, its eigenvalues, and eigenvectors
print("Matrix A:")
print(A)
print("\nEigenvalues of Matrix A:")
print(eigenvalues)
print("\nEigenvectors of Matrix A:")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]

Eigenvalues of Matrix A:
[5. 2.]

Eigenvectors of Matrix A:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## Summary
- We calculated the eigenvalues and eigenvectors of a matrix using NumPy.
- Eigenvectors and eigenvalues are important in linear algebra for understanding matrix properties and transformations.
- This concept is fundamental in many applications, including systems of equations, principal component analysis, and more.